name: Test and Deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Test calculator
      run: python test_calculator.py
    - name: Test web app health
      run: |
        python app.py &
        sleep 2
        curl -f http://localhost:8001/health || exit 1
        pkill -f "python app.py"
    - name: Tests passed
      run: echo "✅ All tests passed, ready for deployment"